/*
Copyright 2022 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	rest "k8s.io/client-go/rest"
	"k8s.io/client-go/tools/cache"

	v1alpha1 "github.com/kcp-dev/kcp/pkg/apis/apiresource/v1alpha1"
)

// NegotiatedAPIResourceLister helps list NegotiatedAPIResources.
// All objects returned here must be treated as read-only.
type NegotiatedAPIResourceLister interface {
	Scoped(scope rest.Scope) NegotiatedAPIResourceLister
	// List lists all NegotiatedAPIResources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NegotiatedAPIResource, err error)
	// Get retrieves the NegotiatedAPIResource from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.NegotiatedAPIResource, error)
	NegotiatedAPIResourceListerExpansion
}

// negotiatedAPIResourceLister implements the NegotiatedAPIResourceLister interface.
type negotiatedAPIResourceLister struct {
	indexer cache.Indexer
	scope   rest.Scope
}

// NewNegotiatedAPIResourceLister returns a new NegotiatedAPIResourceLister.
func NewNegotiatedAPIResourceLister(indexer cache.Indexer) NegotiatedAPIResourceLister {
	return &negotiatedAPIResourceLister{indexer: indexer}
}

func (s *negotiatedAPIResourceLister) Scoped(scope rest.Scope) NegotiatedAPIResourceLister {
	return &negotiatedAPIResourceLister{
		indexer: s.indexer,
		scope:   scope,
	}
}

// List lists all NegotiatedAPIResources in the indexer.
func (s *negotiatedAPIResourceLister) List(selector labels.Selector) (ret []*v1alpha1.NegotiatedAPIResource, err error) {
	appendFunc := func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NegotiatedAPIResource))
	}

	if s.scope == nil {
		err = cache.ListAll(s.indexer, selector, appendFunc)
		return ret, err
	}

	indexValue := s.scope.Name()
	err = cache.ListAllByIndexAndValue(s.indexer, cache.ListAllIndex, indexValue, selector, appendFunc)
	return ret, err
}

// Get retrieves the NegotiatedAPIResource from the index for a given name.
func (s *negotiatedAPIResourceLister) Get(name string) (*v1alpha1.NegotiatedAPIResource, error) {
	key := name
	if s.scope != nil {
		key = s.scope.CacheKey(key)
	}
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("negotiatedapiresource"), name)
	}
	return obj.(*v1alpha1.NegotiatedAPIResource), nil
}
